In [10]:
import numpy as np
import torch
import matplotlib.pylab as plt
import torch.nn as nn

In [12]:
class Model(nn.Module):
    def __init__(self, in_features, out_features):
        super().__init__()
        self.linear = nn.Linear(in_features, out_features)

    def forward(self, x):
        y_pred = self.linear(x)
        return y_pred

In [13]:
torch.manual_seed(59)
model = Model(1,1)
print(model)
print('Weight:', model.linear.weight)
print('Bias:', model.linear.bias)

Model(
  (linear): Linear(in_features=1, out_features=1, bias=True)
)
Weight: Parameter containing:
tensor([[0.1060]], requires_grad=True)
Bias: Parameter containing:
tensor([0.9638], requires_grad=True)


In [14]:
for name, param in model.named_parameters():
    print(name, '\t', param.item())

linear.weight 	 0.10597813129425049
linear.bias 	 0.9637961387634277


In [15]:
x = torch.tensor([2.0])
print(model.forward(x))

tensor([1.1758], grad_fn=<ViewBackward0>)


In [16]:
X = np.linspace(1, 50, 50).reshape(-1,1)
X1 = np.array([X.min(), X.max()])
print(X1)

[ 1. 50.]


In [17]:
w1, b1 = model.linear.weight.item(), model.linear.bias.item()
print(f'Initial Weight:, {w1: 8f}, Initial bias: {b1: 8f}')
print()

Initial Weight:,  0.105978, Initial bias:  0.963796

